#!/bin/sh


#generate tag file for lookupfile plugin
echo -e "!_TAG_FILE_SORTED\t2\t/2=foldcase/" > filenametags
find . -not -regex '.*\.\(png\|gif\)' -type f -printf "%f\t%p\t1\n" | \
       sort -f >> filenametags


#generate tags for ctag plugin.
ctags -R --c++-kinds=+px --fields=+iaS --extra=+q


#Cscope generation
find . -name "*.h" -o -name "*.c" -o -name "*.cc" > cscope.files
cscope -bkq -i cscope.files
